[package]
name = "gitmoto"
version = "0.1.0"
edition = "2021"
description = "TUI for git remote management"

authors = ["Simon Guest <simon.guest@tesujimath.org>"]

[dependencies]
async-stream = "0.3.5"
futures = "0.3.28"
globset = "0.4.14"
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = "0.1.15"
tokio-util = "0.7.9"
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "serde"] }
