[package]
name = "gitmoto"
version = "0.1.0"
edition = "2021"
description = "TUI for git remote management"

authors = ["Simon Guest <simon.guest@tesujimath.org>"]

[dependencies]
futures = "0.3.28"
globset = "0.4.14"
pin-project = "1.1.5"
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["fs"] }
